# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trucquan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import trucquan
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QFileDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1061, 255)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 231, 41))
        self.comboBox.setObjectName("comboBox")
        for index, row in trucquan.df_1.iterrows():
            self.comboBox.addItem(row['TenKhoa'])
        self.comboBox.currentIndexChanged.connect(self.UpdateChuyenNganh)

        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(530, 40, 231, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        for index, row in trucquan.df.iterrows():
            self.comboBox_2.addItem(row['MaDotKS'])

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(810, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.XuatFile)

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        
        
        
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(360, 130, 270, 41))
        self.comboBox_3.setObjectName("comboBox_3")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 130, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.XuatFile_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Xuất file"))
        self.lineEdit.setText(_translate("Dialog", "Khoa "))
        self.lineEdit_2.setText(_translate("Dialog", "Đợt khảo sát"))
        self.lineEdit_3.setText(_translate("Dialog", "Chuyên ngành"))
        self.pushButton_2.setText(_translate("Dialog", "Xuất file theo chuyên ngành"))

    def XuatFile(self) :

        TenKhoa = str(self.comboBox.currentText())
        DotKhaoSat = str(self.comboBox_2.currentText())

        df = trucquan.Tao_df_1(TenKhoa, DotKhaoSat) 
        # Lưu DataFrame vào file Excel
        file_name, _ = QFileDialog.getSaveFileName(self.pushButton, 'Xuất file Excel', '', 'Excel Files (*.xlsx);;All Files (*)')
        if file_name:
            df.to_excel(file_name, index=False)
            print(f'Đã lưu DataFrame vào file Excel: {file_name}')

    def XuatFile_2(self) :

        TenKhoa = str(self.comboBox.currentText())
        DotKhaoSat = str(self.comboBox_2.currentText())
        TenChuyenNganh = str(self.comboBox_3.currentText())

        df = trucquan.Tao_df_2(TenKhoa, DotKhaoSat, TenChuyenNganh) 
        # Lưu DataFrame vào file Excel
        file_name, _ = QFileDialog.getSaveFileName(self.pushButton_2, 'Xuất file Excel', '', 'Excel Files (*.xlsx);;All Files (*)')
        if file_name:
            df.to_excel(file_name, index=False)
            print(f'Đã lưu DataFrame vào file Excel: {file_name}')


    def UpdateChuyenNganh(self) :
        TenKhoa = str(self.comboBox.currentText())
        df_CN = trucquan.ChuyenNganh(TenKhoa)
        self.comboBox_3.clear() 
        for index, row in df_CN.iterrows(): 
            self.comboBox_3.addItem(row['TenChuyenNganh'])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
